### ISSUE TITLE
Traverson .follow() for å navigere linker 

### ISSUE THREAD

**Issue by keawest** [FINTprosjektet/client-example-node#4]
Hei! Jeg bruker nesten samme kode som i eksemplet her men klarer ikke å få traverson til å følge returnerte linker fra rootUrl, er dette noe dere har vært borti?

![Skjermbilde 2021-03-12 132223](https://user-images.githubusercontent.com/42249819/110939853-53a92a00-8336-11eb-9c73-2f2264c3c965.png)

Jeg vil for eksempel navigere fra utdanning/utdanningsprogram/skole og videre til ressursen for linkene i basisgruppe.

![Skjermbilde 2021-03-12 132454](https://user-images.githubusercontent.com/42249819/110940035-92d77b00-8336-11eb-81d1-148bed5d2e63.png)

**Comment by asgeirn** [comment]
Jeg lurer på om det har noe med at våre `_links` peker på arrays, og at Traverson ikke takler det.  Skal se om jeg greier å lete opp mer info.

**Comment by keawest** [comment]
Takk for veldig kjapt svar! Jo det var egentlig noe i den duren vi jeg tenkte. Jeg har også postet en issue om dette på Traverson-hal sin github.

**Comment by keawest** [comment]
saken er nå løst på, https://github.com/traverson/traverson-hal/issues/70 

stenger denne, takk for svar!

**Comment by asgeirn** [comment]
Så bra at du fant en løsning!
